# -*- coding: utf-8 -*-
"""UTSA 2019 Oct - Part4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iw0wdRX3tJhScUnRVimhBfIn8KErpLVX
"""

!rm -rf utsa-workshop-20191024/
!git clone https://github.com/marco-antonio-villegas/utsa-workshop-20191024

!ls utsa-workshop-20191024/data

import pandas as pd
import numpy as np
macro = pd.read_csv('utsa-workshop-20191024/data/nama_10_gdp.tsv', sep="\t", na_values=[': '])
macro = macro.replace(' p', '')

macro = macro.set_index('unit,na_item,geo\\time')

macro.describe()

macro.head()

# macro['COUNTRY'] = macro.iloc[:,0].str.split(',', expand= True).iloc[:,2]
macro['COUNTRY'] = macro.index.str.replace(',','_')

# macro = macro.drop(axis='columns', columns=['unit,na_item,geo\\time'])

# pd.DateaFrame*macro.T

macro.set_index('COUNTRY', drop=True, inplace=True)
macro.head()

macro.T.head()

macro = macro.T

macro = macro.sort_index()

macro.CLV05_MEUR_B1GQ_EU28.astype(float).plot()
macro.CLV05_MEUR_B1GQ_UK.astype(float).plot()
macro.CLV05_MEUR_B1GQ_DE.astype(float).plot()

macro.CLV05_MEUR_B1GQ_UK = macro.CLV05_MEUR_B1GQ_UK.astype(float)

from sklearn.linear_model import LinearRegression
X = macro.CLV05_MEUR_B1GQ_UK.shift(-1)
y = macro.CLV05_MEUR_B1GQ_UK

X.plot()
y.plot()

reg = LinearRegression().fit(X.values[:-1].reshape(-1, 1), y.values[:-1])

reg.score(X.values[:-1].reshape(-1, 1), y.values[:-1])

